# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or create!d alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create!([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create!(name: 'Emanuel', city: cities.first)
# Country.create!(name: 'Canada')
# Country.create!(name: 'United States Of America')
# Country.create!(name: 'United Kingdom')
# Province.create!(country_id: 1, name: 'Alberta')
# Province.create!(country_id: 1, name: 'British Columnbia')
# Province.create!(country_id: 1, name: 'Saskachewan')
# Province.create!(country_id: 1, name: 'Manitoba')
# Province.create!(country_id: 1, name: 'Ontario')
# Province.create!(country_id: 1, name: 'Quebec')
# Province.create!(country_id: 2, name: 'Connecticut')
# Province.create!(country_id: 2, name: 'New York')
# Province.create!(country_id: 2, name: 'New Jersey')
# Province.create!(country_id: 2, name: 'California')
# Province.create!(country_id: 3, name: 'Wales')
# Province.create!(country_id: 3, name: 'England')
# Province.create!(country_id: 3, name: 'Ireland')
# Province.create!(country_id: 3, name: 'Scotland')
# Role.create!(name: 'Company Owner', role_type: 'company')
# Role.create!(name: 'Company Manager', role_type: 'company')
# Role.create!(name: 'Property Manager', role_type: 'property')
# Role.create!(name: 'Board Member', role_type: 'property')
# Role.create!(name: 'Unit Owner', role_type: 'property')
# Role.create!(name: 'Unit Resident', role_type: 'property')
# Service.create!(name: "Auditing and other assurance services")
# Service.create!(name: "Bookkeeping, financial statement compilation, and payroll services")
# Service.create!(name: "Brokerage and other insurance related products")
# Service.create!(name: "Brokerage services for the sale of non-residential real estate")
# Service.create!(name: "Brokerage services for the sale of residential real estate")
# Service.create!(name: "Cable and satellite television subscription services")
# Service.create!(name: "Catering and meal / beverage serving services")
# Service.create!(name: "Civil works services")
# Service.create!(name: "Courier, parcels, and local messenger and delivery services")
# Service.create!(name: "Elevator and escallator services")
# Service.create!(name: "Electrical wiring installation and maintenance services")
# Service.create!(name: "Fire-alarm and other safety systems services")
# Service.create!(name: "Housekeeping and upkeep services")
# Service.create!(name: "Heating, ventillation and air-conditioning services")
# Service.create!(name: "Intercom and security and surveillance systems services")
# Service.create!(name: "Investigation and security services")
# Service.create!(name: "Landscaping and snow removal services")
# Service.create!(name: "Laundry and dry cleaning services")
# Service.create!(name: "Legal services")
# Service.create!(name: "Locksmith")
# Service.create!(name: "Loans")
# Service.create!(name: "Maintenance and repair of personal and household goods")
# Service.create!(name: "Management consulting services")
# Service.create!(name: "Moving services")
# Service.create!(name: "Non-residential rents")
# Service.create!(name: "Office administrative services")
# Service.create!(name: "Other non-life insurance products")
# Service.create!(name: "Plumbing and piping services")
# Service.create!(name: "Postal service")
# Service.create!(name: "Rentals and operating leases of commercial and industrial machinery and equipment, other than office equipment, without operator")
# Service.create!(name: "Rentals and operating leases of consumer goods")
# Service.create!(name: "Rentals and operating leases of office machinery, furniture and equipment")
# Service.create!(name: "Real estate management services - residential")
# Service.create!(name: "Real estate management services - commercial")
# Service.create!(name: "Residential rents")
# Service.create!(name: "Safety inspection services")
# Service.create!(name: "Services related to architecture and engineering")
# Service.create!(name: "Specialized design services")
# Service.create!(name: "Surveying and mapping services")
# Service.create!(name: "Tax preparation and representation services")
# Service.create!(name: "Waste management and remediation services")
# Service.create!(name: "Window washing and cleaning services")
# Service.create!(name: "Wired telephony services")
# Service.create!(name: "Wireless telephone services")
# Category.create!(name: 'company')
# Category.create!(name: 'property manager')
# AddressType.create!(name: 'mailing')
# AddressType.create!(name: 'residential')